### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by luyun181** [XJ-Up/quickupload#1]
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=androidx.activity:activity:1.8.0, variantName=null, artifactFile=C:\Users\x\.gradle\caches\modules-2\files-2.1\androidx.activity\activity\1.8.0\4266e2118d565daa20212d1726e11f41e1a4d0ca\activity-1.8.0.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false,

**Comment by luyun181** [comment]
gradle版本是不是过高

**Comment by XJ-Up** [comment]
根据你提供的报错信息，是activity-1.8.0存在的问题，你是否引入 implementation 'androidx.activity:activity:1.8.0'

**Comment by luyun181** [comment]
是这样的，我的项目是一个旧的java项目。是不是不兼容。我用一个纯kotlin项目就没有问题

**Comment by XJ-Up** [comment]
此项目对java项目是兼容的，你尝试一下移除quickupload后是否能正常运行

**Comment by luyun181** [comment]
移除quickupload依赖就没有问题。在build.gradle中添加依赖sync失败

**Comment by XJ-Up** [comment]
是quickupload中引入 material导致的问题，稍后我会发布新的版本

**Comment by XJ-Up** [comment]
1.2.0版本已更新

**Comment by luyun181** [comment]
好的，谢谢。我晚上尝试一下后给反馈。

**Comment by luyun181** [comment]
Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=androidx.annotation:annotation-experimental:1.4.0, variantName=null, artifactFile=C:\Users\x\.gradle\caches\modules-2\files-2.1\androidx.annotation\annotation-experimental\1.4.0\c7a2038d831d0cfbfb9a440890b287c2e839ecf\annotation-experimental-1.4.0.aar, extractedFolder=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=D:\androidProject\direction_android}, mavenCoordinatesCache=com.android.build.gradle.internal.ide.dependencies.MavenCoordinatesCacheBuildService$Inject@3d3ed6d5)  新的报错

**Comment by XJ-Up** [comment]
感谢你的尝试，我解决问题后通知你

**Comment by XJ-Up** [comment]
久等啦！1.2.1版本已更新，处理了大量老版本兼容性问题，支持minsdk21

**Comment by luyun181** [comment]
集成没报错。应该是可以了。
